import type { CarDef } from "@/lib/car/types";
import car0 from "./01-901-1963.json";
import car1 from "./02-911-swb-1964.json";
import car2 from "./03-911-lwb-1969.json";
import car3 from "./04-carrera-rs-27-1973.json";
import car4 from "./05-g-series-1974.json";
import car5 from "./06-930-turbo-1975.json";
import car6 from "./07-911-sc-1978.json";
import car7 from "./08-carrera-32-1984.json";
import car8 from "./09-964-1989.json";
import car9 from "./10-993-1994.json";
import car10 from "./11-996-1-1998.json";
import car11 from "./12-996-2-2002.json";
import car12 from "./13-997-1-2005.json";
import car13 from "./14-997-2-2009.json";
import car14 from "./15-991-1-2012.json";
import car15 from "./16-991-2-2016.json";
import car16 from "./17-992-1-2019.json";
import car17 from "./18-992-2-2024.json";

/** Traced car definitions by timeline stop id (generated by research/tools/build_app_data.py). */
export const CARS: Record<string, CarDef> = {
  "01-901-1963": car0 as unknown as CarDef,
  "02-911-swb-1964": car1 as unknown as CarDef,
  "03-911-lwb-1969": car2 as unknown as CarDef,
  "04-carrera-rs-27-1973": car3 as unknown as CarDef,
  "05-g-series-1974": car4 as unknown as CarDef,
  "06-930-turbo-1975": car5 as unknown as CarDef,
  "07-911-sc-1978": car6 as unknown as CarDef,
  "08-carrera-32-1984": car7 as unknown as CarDef,
  "09-964-1989": car8 as unknown as CarDef,
  "10-993-1994": car9 as unknown as CarDef,
  "11-996-1-1998": car10 as unknown as CarDef,
  "12-996-2-2002": car11 as unknown as CarDef,
  "13-997-1-2005": car12 as unknown as CarDef,
  "14-997-2-2009": car13 as unknown as CarDef,
  "15-991-1-2012": car14 as unknown as CarDef,
  "16-991-2-2016": car15 as unknown as CarDef,
  "17-992-1-2019": car16 as unknown as CarDef,
  "18-992-2-2024": car17 as unknown as CarDef,
};
